/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author FAMILIA
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     *
     * @return
     */
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/upn.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new javax.swing.JButton();
        icono = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        entrar = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setBackground(new java.awt.Color(204, 204, 0));
        salir.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SALIR_1.png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 120, 60));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tumblr_lexmmsSVKP1qe7uoqo1_250.gif"))); // NOI18N
        icono.setText(" ");
        icono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 130, 130));

        usuario.setFont(new java.awt.Font("Kristen ITC", 3, 18)); // NOI18N
        usuario.setForeground(new java.awt.Color(51, 255, 0));
        usuario.setText("USUARIO:");
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, -1));

        contraseña.setFont(new java.awt.Font("Kristen ITC", 3, 18)); // NOI18N
        contraseña.setForeground(new java.awt.Color(102, 0, 102));
        contraseña.setText("CONTRASEÑA:");
        getContentPane().add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 220, -1));

        user.setBackground(new java.awt.Color(255, 102, 102));
        user.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 180, 30));

        entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ENTRAR_1.png"))); // NOI18N
        entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarMouseClicked(evt);
            }
        });
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        getContentPane().add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 120, 60));

        pass.setBackground(new java.awt.Color(102, 102, 255));
        pass.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 130, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ALEGRE.png"))); // NOI18N
        fondo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 350, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed

        
        // TODO add your handling code here:
    }//GEN-LAST:event_entrarActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_userActionPerformed

    private void entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarMouseClicked
        // TODO add your handling code here:
        
        String usuario1= "informatica2";
        String contraseña1= "contraseña";
        
        String password = new String(pass.getPassword());
        
        if(user.getText().equals(usuario1)&& password.equals(contraseña1)){
                        
        panel2 juan  = new panel2();
        juan.setVisible(true);
        dispose();
        
        } else{
                      
            JOptionPane.showMessageDialog(this, "Usuario o clave incorrecto...");
        }        
                
                
        
        
        
    }//GEN-LAST:event_entrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contraseña;
    private javax.swing.JButton entrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel icono;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton salir;
    private javax.swing.JTextField user;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
