/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author FAMILIA
 */
public class panel5 extends javax.swing.JFrame {

    /**
     * Creates new form panel5
     */
    public panel5() {
        initComponents();
           this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir2 = new javax.swing.JButton();
        nombre2 = new javax.swing.JTextField();
        apellido2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        parentesco = new javax.swing.JComboBox();
        familiar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        foticos2 = new javax.swing.JLabel();
        botonfotos = new javax.swing.JButton();
        fondo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SALIR_1.png"))); // NOI18N
        salir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir2ActionPerformed(evt);
            }
        });
        getContentPane().add(salir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 120, 60));
        getContentPane().add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 300, 30));
        getContentPane().add(apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 300, 30));

        jTextField3.setText("jTextField3");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 210, 30));

        parentesco.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        parentesco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Madre", "Padre", "Hermano(a)", "Abuelo(a)", "Responsable" }));
        getContentPane().add(parentesco, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 160, -1));

        familiar.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        familiar.setForeground(new java.awt.Color(255, 255, 255));
        familiar.setText("Parentesco");
        getContentPane().add(familiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 120, 20));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Apellidos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 110, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Nombres");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 160, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 0));
        jLabel3.setText("Telefono");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 120, 30));

        foticos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono-adultos-web-optfinal_1.jpg"))); // NOI18N
        foticos2.setText("fotos");
        foticos2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)), "Fotografias", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comic Sans MS", 0, 10), new java.awt.Color(153, 153, 255))); // NOI18N
        getContentPane().add(foticos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 150, 160));

        botonfotos.setBackground(new java.awt.Color(0, 204, 204));
        botonfotos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        botonfotos.setForeground(new java.awt.Color(51, 51, 255));
        botonfotos.setText("Cargar Foto");
        botonfotos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonfotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonfotosActionPerformed(evt);
            }
        });
        getContentPane().add(botonfotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 130, 30));

        fondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Superb-digital-design-abstract-background_1.jpg"))); // NOI18N
        getContentPane().add(fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salir2ActionPerformed

    File fichero1;
    private void botonfotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonfotosActionPerformed
            // TODO add your handling code here: codigo pra fotos...
        
     int resultado1;
     cargarfotos ventani = new cargarfotos();
     FileNameExtensionFilter filtro1 = new FileNameExtensionFilter("JPG y PNG ","jpg","png");
     
        
        ventani.cargar.setFileFilter(filtro1);
        resultado1 = ventani.cargar.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == resultado1){
            
            fichero1 = ventani.cargar.getSelectedFile();
            
            try {
                ImageIcon icon1 = new ImageIcon(fichero1.toString());
                Icon icono = new ImageIcon(icon1.getImage().getScaledInstance(foticos2.getWidth(),foticos2.getHeight(), Image.SCALE_DEFAULT));
                foticos2.setText(null);
                foticos2.setIcon(icono);
                
            }catch(Exception ex){
            
                JOptionPane.showMessageDialog(null," Upss,, error abriendo la imagen seleccionada" + ex);
        }
        
    }                                    
    
    }//GEN-LAST:event_botonfotosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new panel5().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido2;
    private javax.swing.JButton botonfotos;
    private javax.swing.JLabel familiar;
    private javax.swing.JLabel fondo4;
    private javax.swing.JLabel foticos2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField nombre2;
    private javax.swing.JComboBox parentesco;
    private javax.swing.JButton salir2;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
