/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author FAMILIA
 */
public class panel2 extends javax.swing.JFrame {

    /**
     * Creates new form panel2
     */
    public panel2() {
        initComponents();
         this.setLocationRelativeTo(null); // para que quede en el centro 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        adelante = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaregistro = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        fiesta = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        feliminar = new javax.swing.JButton();
        numeros = new javax.swing.JLabel();
        contador = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fondo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("BIENVENIDO AL SISTEMA (°__-)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 650, 60));

        adelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ADELANTE.png"))); // NOI18N
        adelante.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(adelante, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 70, 70));

        tablaregistro.setBackground(new java.awt.Color(153, 153, 153));
        tablaregistro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));
        tablaregistro.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tablaregistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaregistro);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 430, 200));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("LISTA DE PROGRAMACION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 360, -1));

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ATRAS.png"))); // NOI18N
        atras.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 70, 70));

        fiesta.setBackground(new java.awt.Color(0, 204, 204));
        fiesta.setForeground(new java.awt.Color(0, 0, 255));
        fiesta.setText("AGREGAR FIESTA");
        fiesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiestaActionPerformed(evt);
            }
        });
        getContentPane().add(fiesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, 70));

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SALIR_1.png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 120, 60));

        feliminar.setBackground(new java.awt.Color(153, 153, 255));
        feliminar.setForeground(new java.awt.Color(0, 0, 51));
        feliminar.setText("ELIMINAR FIESTA");
        feliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feliminarActionPerformed(evt);
            }
        });
        getContentPane().add(feliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 120, 70));

        numeros.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        numeros.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
        getContentPane().add(numeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 90, 70));

        contador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1.png"))); // NOI18N
        getContentPane().add(contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 160, 250));

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 50, 50));

        fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/colores.jpg"))); // NOI18N
        getContentPane().add(fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 722, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void feliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feliminarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
        
    }//GEN-LAST:event_salirActionPerformed

    private void fiestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiestaActionPerformed
        // TODO add your handling code here:
        
        panel3 juan3  = new panel3();
        juan3.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_fiestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adelante;
    private javax.swing.JButton atras;
    private javax.swing.JLabel contador;
    private javax.swing.JButton feliminar;
    private javax.swing.JButton fiesta;
    private javax.swing.JLabel fondo3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numeros;
    private javax.swing.JButton salir;
    private javax.swing.JTable tablaregistro;
    // End of variables declaration//GEN-END:variables
}
