/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
//import java.io.BufferedReader;
//import java.io.FileReader;
/**
 *
 * @author FAMILIA
 */
public class panel4 extends javax.swing.JFrame {
    
int contador=0;

File archivo1;
String Ruta;
String[] nombre;
String[] apellido;
String[] edad;
String[] genero;
String[] juguetes;
String[] regalo;
String[] dulce;
String[] globo;
String[] piñata;
String[] television;
String[] videojuegos;
String[] deporte;
String BuscarTemp;

    Boolean Seguir;
    BufferedWriter bw;
    BufferedReader br;
    FileReader fr;
    String Buscar;
    String Linea;
    String tmp1,tmp2,tmp3,tmp4,tmp5,tmp6;
    String Ruta2;
   
    /**
     * Creates new form panel4
     */
    public panel4() {
        initComponents();
        String Ruta = "d:\\datos.txt";
        archivo1 = new File(Ruta);
       nombre = new String[10] ;
       apellido = new String[10] ;
       edad = new String[10] ;
       genero = new String[10] ;
       juguetes = new String[10] ;
       regalo = new String[10] ;
       dulce = new String[10] ;
       globo = new String[10] ;
       piñata = new String[10] ;
       television = new String[10] ;
       videojuegos = new String[10] ;
       deporte = new String[10] ;
       
       contador = 0;
        int i=0;
        Scanner ee = null;
        try{
            ee = new Scanner(new File("d:\\datos.txt"));
            while (ee.hasNext())
            {
               // String tmp[] = ee.next().split(","); 
                nombre[i] = ee.next();;
                apellido[i] = ee.next();;
                edad[i] = ee.next();;
                genero[i] = ee.next();;
                juguetes[i] = ee.next();;
                regalo[i] = ee.next();;
                dulce[i] = ee.next();;
                globo[i] = ee.next();;
                piñata[i] = ee.next();;
                television[i] = ee.next();;
                videojuegos[i] = ee.next();;
                deporte[i] = ee.next();;
                //String tmp[] = ee.next().split(","); 
               // nombre[i] = tmp[0];
               // apellido[i] = tmp[1];
               // edad[i] = tmp[2];
               // genero[i] = tmp[3];
               // juguetes[i] = tmp[4];
               // regalo[i] = tmp[5];
               // dulce[i] = tmp[6];
               // globo[i] = tmp[7];
              //  piñata[i] = tmp[8];
                //television[i] = tmp[9];
              //  videojuegos[i] = tmp[10];
               // deporte[i] = tmp[11];
                i +=1;
                
            }
            contador = i;
        } catch (Exception e)
        {
            mensajerror.setText("Error en archivo : " + Ruta);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SALIR = new javax.swing.JButton();
        buscador = new javax.swing.JButton();
        casilla1 = new javax.swing.JTextField();
        casilla2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        casilla4 = new javax.swing.JTextField();
        casilla5 = new javax.swing.JTextField();
        casilla7 = new javax.swing.JTextField();
        casilla8 = new javax.swing.JTextField();
        casilla12 = new javax.swing.JTextField();
        casilla11 = new javax.swing.JTextField();
        casilla9 = new javax.swing.JTextField();
        casilla10 = new javax.swing.JTextField();
        casilla6 = new javax.swing.JTextField();
        casilla3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        mensajerror = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SALIR_1.png"))); // NOI18N
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 120, 60));

        buscador.setText("filtrar");
        buscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorActionPerformed(evt);
            }
        });
        getContentPane().add(buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        casilla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla1ActionPerformed(evt);
            }
        });
        getContentPane().add(casilla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 100, -1));

        casilla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla2ActionPerformed(evt);
            }
        });
        getContentPane().add(casilla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 100, -1));

        jLabel2.setText("nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel3.setText("apellido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));
        getContentPane().add(casilla4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 90, -1));
        getContentPane().add(casilla5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 80, -1));
        getContentPane().add(casilla7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 90, -1));
        getContentPane().add(casilla8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 90, -1));
        getContentPane().add(casilla12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 90, -1));
        getContentPane().add(casilla11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 80, -1));
        getContentPane().add(casilla9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 80, -1));
        getContentPane().add(casilla10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 80, -1));
        getContentPane().add(casilla6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 90, -1));

        casilla3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casilla3ActionPerformed(evt);
            }
        });
        getContentPane().add(casilla3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 80, -1));

        jLabel1.setText("GUSTOS DEL NIÑO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel4.setText("SISTEMA DE BUSQUEDA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 92, 350, 20));

        mensajerror.setText(":o");
        getContentPane().add(mensajerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SALIRActionPerformed

    private void buscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorActionPerformed
        // TODO add your handling code here:
        try
        {
            archivo1 = new File(Ruta);
            fr = new FileReader (archivo1);
            br = new BufferedReader(fr);
            Buscar = casilla1.getText();
            BuscarTemp = casilla1.getText();
            String Line;

            while((Line=br.readLine()) !=null)
            {

                String [] Datosp =Line.split(",");
                
                if(Datosp[0].equals(Buscar))
                {
                    nombre.setText(Datosp[0]);
                    apellido.setText(Datosp[1]);
                    
                   
                    
                    
                    if(Datosp[4].equals("piñata")){casilla4+("");casilla4.addItem("piñata");;}
                    else if (Datosp[4].equals("Deportes")){Gusto1.removeAllItems();Gusto1.addItem("Deportes");Gusto1.addItem("Vehiculos");Gusto1.addItem("Caricaturas");Gusto1.addItem("Videojuegos");}
                    else if (Datosp[4].equals("Caricaturas")){Gusto1.removeAllItems();Gusto1.addItem("Caricaturas");Gusto1.addItem("Vehiculos");Gusto1.addItem("Deportes");Gusto1.addItem("Videojuegos");}
                    else if (Datosp[4].equals("Videojuegos")){Gusto1.removeAllItems();Gusto1.addItem("Videojuegos");Gusto1.addItem("Vehiculos");Gusto1.addItem("Caricaturas");Gusto1.addItem("Deportes");}
                    
                    else if (Datosp[4].equals("Muñecas")){Gusto1.removeAllItems();Gusto1.addItem("Muñecas");Gusto1.addItem("Vestidos");Gusto1.addItem("Caricaturas");Gusto1.addItem("Animales");}
                    else if (Datosp[4].equals("Vestidos")){Gusto1.removeAllItems();Gusto1.addItem("Vestidos");Gusto1.addItem("Muñecas");Gusto1.addItem("Caricaturas");Gusto1.addItem("Animales");}
                    else if (Datosp[4].equals("Caricaturas")){Gusto1.removeAllItems();Gusto1.addItem("Caricaturas");Gusto1.addItem("Vestidos");Gusto1.addItem("Muñecas");Gusto1.addItem("Animales");}
                    else if (Datosp[4].equals("Animales")){Gusto1.removeAllItems();Gusto1.addItem("Animales");Gusto1.addItem("Vestidos");Gusto1.addItem("Caricaturas");Gusto1.addItem("Muñecas");}
                    
                    
                    
                    
                }

                else if (Datosp[1].equals(Buscar))
                {
                    
        
       
			
		
          // nombre.resultset.first();
          // String igual = "no";
          // int largo_busqueda = casilla1.getText().length();
          // while (igual == "no"){
            //   String = buscado = nombre.resultset
          // }
        
       // for (int i = 0; i<contador; i++){
          //if (casilla1.getText().equals(nombre[i])){
             // if (casilla2.getText().equals(apellido[i]))
            //{
                //casilla1.setText(nombre[i]);
                //casilla2.setText(apellido[i]);
               // casilla3.setText(edad[i]); 
               // casilla4.setText(genero[i]); 
               // casilla5.setText(juguetes[i]);
               // casilla7.setText(regalo[i]);
               // casilla8.setText(dulce[i]);
              //  casilla9.setText(globo[i]);
             //   casilla10.setText(piñata[i]);
             //   casilla11.setText(television[i]);
             //   casilla12.setText(videojuegos[i]);
                
          //}   
          //    }
         // else
           ///mensajerror.setText("LOS DATOS NO CORRESPONDEN");
                 // }
         }  
            }
                 } catch (FileNotFoundException ex) { 
        Logger.getLogger(panel4.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) { 
        Logger.getLogger(panel4.class.getName()).log(Level.SEVERE, null, ex);
    } 
    }//GEN-LAST:event_buscadorActionPerformed

    private void casilla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla1ActionPerformed

    private void casilla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla2ActionPerformed

    private void casilla3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casilla3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casilla3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel4().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SALIR;
    private javax.swing.JButton buscador;
    private javax.swing.JTextField casilla1;
    private javax.swing.JTextField casilla10;
    private javax.swing.JTextField casilla11;
    private javax.swing.JTextField casilla12;
    private javax.swing.JTextField casilla2;
    private javax.swing.JTextField casilla3;
    private javax.swing.JTextField casilla4;
    private javax.swing.JTextField casilla5;
    private javax.swing.JTextField casilla6;
    private javax.swing.JTextField casilla7;
    private javax.swing.JTextField casilla8;
    private javax.swing.JTextField casilla9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mensajerror;
    // End of variables declaration//GEN-END:variables
}
